// mega123-art/cognitomarket/CognitoMarket-0c18b60b1296623dd08053b0e2c9d5c137ff1823/app/src/components/app-footer.tsx
import React from 'react'

export function AppFooter() {
  return (
    <footer className="text-center p-2 bg-neutral-100 dark:bg-neutral-900 dark:text-neutral-400 text-xs">
      {/* Removed generated by text */}
    </footer>
  )
}
